import type { NextPage } from 'next'
import Head from 'next/head'

export const Meta: NextPage = () => {
  return (
    <Head>
      <title>S10N App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}
